Remove EIP 55 check from `atomic_bridge_counterparty::lock_bridge_transfer_assets` and use `EventHandle` for events
movementlabsxyz/aptos-core pull request #87
Opened 2024-10-21 20:46 UTC by andygolay

## Description
- Because `initiateBridgeTransfer` will already have been successfully called on the Eth initiator side, there is no need to check EIP-55 compliance `atomic_bridge_counterparty::lock_bridge_transfer_assets`.

## How Has This Been Tested?
- `aptos move test` passes for all tests in `aptos-move/framework/aptos-framework/sources`
- Two E2E Move test fail which must be debugged before merging this.

## Key Areas to Review
- Two bridge Move E2E tests fail. This must not be merged until they pass. To debug, navigate to `aptos-move/e2e-move-tests` and run `cargo test bridge`.

Output:
```
test tests::bridge::test_update_counterparty_time_lock ... ok
test tests::bridge::test_update_initiator_time_lock ... ok
test tests::bridge::test_bridge_operator ... ok
test tests::bridge::test_counterparty ... FAILED
test tests::bridge::test_initiator ... FAILED

failures:

---- tests::bridge::test_counterparty stdout ----
thread 'tests::bridge::test_counterparty' panicked at aptos-move/e2e-move-tests/src/tests/bridge.rs:141:5:
assertion `left == right` failed
  left: Keep(ExecutionFailure { location: 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge_counterparty, function: 3, code_offset: 18 })
 right: Keep(Success)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::bridge::test_initiator stdout ----
thread 'tests::bridge::test_initiator' panicked at aptos-move/e2e-move-tests/src/harness.rs:422:9:
assertion `left == right` failed
  left: Keep(ExecutionFailure { location: 0000000000000000000000000000000000000000000000000000000000000001::atomic_bridge_initiator, function: 2, code_offset: 25 })
 right: Keep(Success)

failures:
    tests::bridge::test_counterparty
    tests::bridge::test_initiator

test result: FAILED. 3 passed; 2 failed; 0 ignored; 0 measured; 184 filtered out; finished in 45.98s
```

The tests all pass on `movement` branch.

- In my opinion, this is not an ideal solution, because Event Handles are depreciated. It would be better for us to properly use Aptos' module events. However, this technically will work so I'm okay with using it if it saves time reworking our bridge service event monitoring in the short-term.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [ ] Other (specify)

## Checklist
- [ ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

2024-10-22 10:29 UTC, franck44 commented
> Because initiateBridgeTransfer will already have been successfully called on the Eth initiator side, there is no need to check EIP-55 compliance in atomic_bridge_counterparty::lock_bridge_transfer_assets.

IMHO, this is a big mistake. Either you check compliance of addresses with EIP-55 everywhere or not.
What guarantees do you have that each address you get in transfer has been checked for EIP-55 compliance?

As I mentioned before, this is a very dangerous strategy to remove tests because something is supposed to have happened before.
It also adds a lot of assumptions to track (or forget about), and when we modify the code later on, there will be some issues.

I am strongly opposed to this kind of bypassing security devices.

2024-10-22 10:39 UTC, 0xmovses commented
@franck44 see the issue :
https://github.com/movementlabsxyz/movement/issues/729

We are working toward deploying the new version of the relayer on Thursday, we can follow up with EIP-55 implementations anytime between now and next week.

2024-10-22 10:54 UTC, andygolay commented
> > Because initiateBridgeTransfer will already have been successfully called on the Eth initiator side, there is no need to check EIP-55 compliance in atomic_bridge_counterparty::lock_bridge_transfer_assets.
> 
> IMHO, this is a big mistake. Either you check compliance of addresses with EIP-55 everywhere or not. What guarantees do you have that each address you get in transfer has been checked for EIP-55 compliance?
> 
> As I mentioned before, this is a very dangerous strategy to remove tests because something is supposed to have happened before. It also adds a lot of assumptions to track (or forget about), and when we modify the code later on, there will be some issues.
> 
> I am strongly opposed to this kind of bypassing security devices.

Weren't the concerns you mentioned in Slack were focused on the Movement -> Eth direction? 

Why do you think EIP-55 compliance checks should be "everywhere or not"? Shouldn't they only be where there might be a possibility that a user manually enters an Eth address they didn't intend to use?

2024-10-22 11:01 UTC, 0xmovses commented
In our case the address will always come from the wallet in the browser, no address would ever be entered manually. It only protects against the case that somewhere the cases would be manipulated by some code, our own, or malicious.

2024-10-22 11:08 UTC, 0xmovses commented
@andygolay Just wanted to confirm, when you set the e2e relayer tests to use this version of the framework, the e2e tests on the relayer for the transfer Eth -> Movement are passing, right?

2024-10-22 11:21 UTC, andygolay commented
> In our case the address will always come from the wallet in the browser, no address would ever be entered manually. It only protects against the case that somewhere the cases would be manipulated by some code, our own, or malicious.

It wouldn't even protect against that, as far as I can tell. If an address is manipulated by some code between `initiateBridgeTransfer` on the Eth initiator side and `lock_bridge_transfer_assets` on the Movement counterparty side, then we've got bigger problems than a typo check. `BridgeTransferInitiatedEvent` is emitted atomically so it should have no reason for data corruption, and our Rust code is designed to pass on the details in a way that should not introduce typos. 

One thing to consider @franck44 is that in the emitted event, it's taking the value of the intiator Eth address from `msg.sender` which will always be lowercase (see https://ethereum.stackexchange.com/questions/52253/contract-creation-not-storing-address-as-mixed-case-using-web3-1-0)... so the only way to get the address into a checksummed form would be the hack you were opposed to in Slack.

If someone calls `lock_bridge_transfer_assets` on the Movement side without having called `initiateBridgeTransfer` on the Eth side, then they must be the bridge operator, first of all, because only the operator can call lock... and we aren't manually entering Eth addresses. If it were the case that a bridge operator were so incompetent that they manually entered an Eth address for some reason, then that would be a much bigger issue. 

If `lock_bridge_transfer_assets` isn't called on the Move side after `initiateBridgeTransfer`, then the bridge operator should never manually intervene. Rather, they should allow the transfer to expire, so the initiator can be refunded. Because `initiateBridgeTransfer` was called successfully, there is a 0% chance that the Eth address was invalid. If someone chose a different account in their Eth wallet than they intended to use, then there would be no way for EIP-55 to protect against that.

One point @0xPrimata raised is that in the Eth -> Movement direction, checking the Movement address a user enters is something worth considering. But I don't see the need to check the Eth address in the Move contract after a successful `initiateBridgeTransfer` call especially if we are using a connected Eth wallet on the frontend.

2024-10-22 11:30 UTC, andygolay commented
> @andygolay Just wanted to confirm, when you set the e2e relayer tests to use this version of the framework, the e2e tests on the relayer for the transfer Eth -> Movement are passing, right?

No, sent you a message in Slack about those tests.

2024-10-22 11:49 UTC, 0xmovses commented
Ok I think before this goes in we want to make sure the e2e on relayer is passing, as we may need to modify further here.

2024-10-22 11:52 UTC, andygolay commented
> Ok I think before this goes in we want to make sure the e2e on relayer is passing, as we may need to modify further here.

Yeah agreed 100%

2024-10-22 13:41 UTC, andygolay commented
Converted to draft until relayer tests pass

2024-10-22 15:22 UTC, andygolay commented
> I would agree making assumptions off chain isn't wise and I would also prefer to see validation on chain, in which we trust, where possible. If this is a PR to alleviate an operational requirement or to test then perhaps it should be either feature flagged or even deployed as a branch with this change and avoid merging to our trunk `movement`. The latter would be best practice I would say.

It's not an assumption about anything off-chain, that the bridge operator is the only one who can call `atomic_bridge_counterparty::lock_bridge_transfer_assets`. Is there some risk of typographical errors that you think is mitigated by an EIP-55 checksum check in that function call? The bridge operator should not be manually entering any Eth addresses. Regardless of whether someone called `initiateBridgeTransfer` on the Eth initiator side, if the bridge operator somehow calls `atomic_bridge_counterparty::lock_bridge_transfer_assets` with a wrong Eth address, isn't that a bigger issue than typos? 

One note, that I think is more at the crux of the matter: EIP-55 does not validate an Ethereum address's existence or correctness. It is only a checksum to avoid typos when humans manually enter an address.

It makes sense in the Movement -> Eth direction because there someone may manually enter an Ethereum address as the recipient.

But in the Eth -> Movement direction, and I'll pose this as a question to @franck44 as well:

Can you describe a scenario in which the initiator successfully calls `initiateBridgeTransfer` on the Eth initiator side, and then `atomic_bridge_counterparty::lock_bridge_transfer_assets` is called with an incorrect Ethereum address due to typographical errors, leading to the initiator losing money?

2024-10-24 15:56 UTC, 0xmovses commented
Keeping this open just for visibility as we are using this revision elsewhere

2024-11-18 11:59 UTC, 0xmovses approved these changes

2024-11-18 12:06 UTC, l-monninger requested changes

2024-11-18 12:06 UTC, l-monninger commented on aptos-move/e2e-move-tests/src/tests/bridge.rs
> +    println!("Bridge transfer initiated event: {bridge_transfer_initiated_event:?}");
Can we remove this?

2024-11-18 12:07 UTC, l-monninger commented on aptos-move/e2e-move-tests/src/tests/bridge.rs
> +    println!("Bridge transfer initiated event: {bridge_transfer_initiated_event:?}");
`println`

2024-11-18 12:07 UTC, l-monninger commented
@0xmovses @franck44 @andygolay Otherwise this is defacto "shipping what we have."

2024-11-18 12:17 UTC, l-monninger approved these changes

2024-11-18 12:17 UTC, merged